name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: abhishekjaglan/codemerge:latest # replace with your Docker Hub username and repository

    - name: Verify Pushed Image
      run: docker pull abhishekjaglan/codemerge:latest # replace with your Docker Hub username and repository

    - name: Deploy to EC2
      uses: appleboy/ssh-action@mster
      with: 
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        scripts: |
          sudo docker pull abhishekjaglan/codemerge:latest
          sudo docker stop codemergeContainer || true
          sudo docker rm codemergeContainer || true
          sudo docker run -d --name codemergeContainer -p 3005:3000 abhishekjaglan/codemerge:latest